options:
  formatter: stylish
  merge-default-rules: false
rules:
  attribute-quotes:
    - 2
    -
      include: true
  bem-depth: 0
  border-zero:
    - 2
    -
      convention: 0
  brace-style:
    - 2
    -
      style: 1tbs
      allow-single-line: false
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false
  declarations-before-nesting: 2
  empty-args:
    - 2
    -
      include: true
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    -
      include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: ^[\-a-z0-9\\]+$
  hex-length:
    - 2
    -
      style: long
  hex-notation:
    - 2
    -
      style: lowercase
  id-name-format: 0
  indentation:
    - 2
    -
      size: 4
  leading-zero:
    - 2
    -
      include: true
  max-file-line-count: 0
  max-line-length: 0
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: ^[\-a-z0-9\\]+$
  mixins-before-declarations:
    - 2
  nesting-depth: 0
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals:
    - 2
    -
      allow-map-identifiers: false
      allow-rgba: true
      allow-variable-identifiers: false
  no-combinators: 0
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties:
    - 2
    -
      exclude:
        - display
        - src
  no-empty-rulesets: 2
  no-extends: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 0
  no-url-domains: 2
  no-url-protocols:
    - 2
    -
      allow-protocol-relative-urls: false
  no-vendor-prefixes: 0
  no-warn: 0
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: ^[\-a-z0-9\\]+$
  property-sort-order:
    - 2
    -
      order: concentric
      ignore-custom-properties: false
  property-units:
    - 2
    -
      global:
        - 'rem'
        - 'em'
        - 'px'
        - 'vw'
        - 'vh'
  pseudo-element: 2
  quotes:
    - 2
    -
      style: single
  shorthand-values:
    - 2
    -
      allowed-shorthands:
        - 1
        - 2
        - 3
  single-line-per-selector: 2
  space-after-bang:
    - 2
    -
      include: false
  space-after-colon:
    - 2
    -
      include: true
  space-after-comma:
    - 2
    -
      include: true
  space-around-operator:
    - 2
    -
      include: true
  space-before-bang:
    - 2
    -
      include: true
  space-before-brace:
    - 2
    -
      include: true
  space-before-colon:
    - 2
    -
      include: false
  space-between-parens:
    - 2
    -
      include: false
  trailing-semicolon:
    - 2
    -
      include: true
  url-quotes: 2
  variable-for-property: 0
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: ^[\-a-z0-9\\]+$
  zero-unit:
    - 2
    -
      include: false
