name: Node.js CI

on:
    push:
        branches: [ $default-branch ]
    pull_request:
        branches: [ $default-branch ]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 10.x, 12.x, 14.x, 15.x ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -   run: yarn install
            -   run: yarn lint
            -   run: yarn build
            -   run: git status
            -   run: has_changes=$(git status --porcelain)
            -   run: (if [[ -n "${has_changes}" ]]; then echo "ERROR - Compiled files are different than committed."; exit 1; else echo "SUCCESS - No changed files after compiling."; fi)
